name: GitHub Actions Build and Deploy Hexo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        lfs: true
    - name: Install and BuildA 🔧 # Tsshis example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
        npm install
        npm run build
        npm run build-storybook
        rm -rf xyx-ui/.git
        rm -rf xyx-ui/.github
        rm -rf xyx-ui/.gitignore
    - name: Deploy
      uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        site-directory: ./storybook-static
        commit-message: fuck
        deploy-branch: gh-pages
